### PR TITLE
cleanup readme and rework BCL tasks

### PR DESCRIPTION
**Pull request by kflemin**
- remove old BCL stuff
- rework README to add compatibility matrix and openstudio contribution policy link

This will work once BCL2 is transferred to BCL url

TODO: update gemspec with new version of bcl-gem when that's released

### CODE REVIEW

**Review by nllong — APPROVED** [review]
this is great, thanks for cleaning up the BCL code!

**Comment by nllong** [comment]
@kflemin -- any reason not to merge this? Waiting until BCL 2.0 release?

**Comment by kflemin** [comment]
@nllong exactly

**Comment by kflemin** [comment]
@nllong, bcl 2.0 is live at the bcl.nrel.gov URL. I'm going to go ahead and merge this.

**Comment by nllong** [comment]
sweet!

**Pull request merged**
