### PR TITLE
restoring missing BCL update functionality

### PR DESCRIPTION
**Pull request by kflemin**
restoring missing BCL update functionality after a very bad merge

### CODE REVIEW

**Comment by kflemin** [comment]
@nllong, if you can review and then release that would be great.  The gem as it is currently won't push any updated content to BCL.😬

**Comment by tijcolem** [comment]
@nllong @kflemin Let me know if you feel the updated release (0.2.4?) should be included in 3.0.1 OpenStudio and I'll try to include it.

**Comment by nllong** [comment]
Released OS-ext 0.2.4 (https://rubygems.org/gems/openstudio-extension/versions/0.2.4) and added PR in openstudio-gems (https://github.com/NREL/openstudio-gems/pull/27).

Nick

Da: TJC <notifications@github.com>
Risposta: NREL/openstudio-extension-gem <reply@reply.github.com>
Data: sabato 20 giugno 2020 09:05
A: NREL/openstudio-extension-gem <openstudio-extension-gem@noreply.github.com>
Cc: "Long, Nicholas" <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [NREL/openstudio-extension-gem] restoring missing BCL update functionality (#69)


@nllong<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnllong&data=02%7C01%7Cnicholas.long%40nrel.gov%7C5a3307dc8bf54e010d2d08d8152b62b9%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637282623385808204&sdata=Ey3lOnUrqUZJs%2BGYZcRMcUctvSM4n9QLtOtBR4kksGY%3D&reserved=0> @kflemin<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkflemin&data=02%7C01%7Cnicholas.long%40nrel.gov%7C5a3307dc8bf54e010d2d08d8152b62b9%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637282623385808204&sdata=Zu%2FZdmzHdtgdLC3onPFvVJs6flFIg7UNSeSe%2Bxy%2F4OA%3D&reserved=0> Let me know if you feel the updated release (0.2.4?) should be included in 3.0.1 OpenStudio and I'll try to include it.

**Comment by kflemin** [comment]
@nllong thank you!!

**Pull request merged**
