### PR TITLE
Update os_lib_model_generation.rb

### PR DESCRIPTION
**Pull request by mdahlhausen**
rubocop edits and alignment with version in ComStock

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@mdahlhausen and @asparke2 not sure what Comstock is here vs. the 90.1 and DOE Ref, but are se sure we don't want those in the extended list of vintages that isn't used on the general purpose measures on BCL. The extended list was specifically made to support what was used for comstock.
https://github.com/NREL/openstudio-extension-gem/blob/update_os_lib_model_generation/lib/openstudio/extension/core/os_lib_model_generation.rb#L153-L170

**Comment by DavidGoldwasser** [comment]
This is going to have merge conflicts with this branch. This branch restructured the create_bar to have sub methods and to work with a ratio of building types or ratio of unknown number of spaces types. I also added to spec in this branch to test create_bar and create_typical in the gem. I'd like the pull request with this to go through first, as it will make testing of these changes easier. 
https://github.com/NREL/openstudio-extension-gem/tree/bar_from_space_type_ratios

I know the merge conflict is only this file, not sure how involved addressing the conflicts will be.

**Comment by mdahlhausen** [comment]
@DavidGoldwasser I don't the merge conflicts will be substantial.  The changes did not touch geometry except for some rubocop edits.

As for the extended definitions - if possible, I'd like the resource file to be identical across repositories.  If that isn't possible, then we can remove the extended version from the specific measures (or copy in the file to the resources for that measure).  It's just if I add or make changes to the workflow, I want them reflected everywhere.

**Comment by DavidGoldwasser** [comment]
@mdahlhausen " I'd like the resource file to be identical across repositories"  This code only exist here in extension gem and not anywhere else?

"remove the extended version from the specific measures" The idea of the extended flag was for this. The combined DOE/DEER version used by ComStock uses extended values, the more general use version that is DOE specific or DEER specific doesn't use extended arguments. This way I can one list of standards to maintain that is used by all measures.

I think the main question of putting these new values in the extended section or not is if they are documented and we want the general public to use them. What makes the ComStock version of the DOE and ASHRAE 90.1 different? Are they starting to separate from what is used for prototype and baseline? Maybe they should be general use but it isn't clear to me what they are yet. If they are better to use then we should list only them and move the non-comstock version to extended. Two sets is a little confusing.

**Comment by mdahlhausen** [comment]
The os_lib_model_generation.rb also exists on the ComStock repo.
I think it is ok to include ComStock templates in the public version.  They are different from the prototypes, and are quasi-documented through the calibration reports from the end-use load profiles project.  They more accurately reflect existing buildings.  People shouldn't be using that measure anyways unless they have a specific use case in mind.

**Comment by DavidGoldwasser** [comment]
@mdahlhausen "People shouldn't be using that measure". Do you mean the combined DOE/DEER one or do you mean th more basic "Create Typical From DOE" and Create Typical form DEER". "Create Typical From DOE" is used by at least a dozen intern and external projects.

**Comment by mdahlhausen** [comment]
What I mean is, the only use for these measures for specific comparison projects.  The details of the project should dictate whether you want DOE, ComStock, or DEER prototypes.  If they don't know which one they need, they don't know enough about their project to warrant using a measure like create typical.

**Comment by DavidGoldwasser** [comment]
@mdahlhausen Can you provide some information to differentiate Comstock from DOE that I can add to these measures. For example does it impact just loads, or also schedules, constructions, and HVAC systems? A link to documentation would also work instead of embedding description text in the readme.erb. If i do embed text I may even write it in extension gem in `get_doe_template_description method` so I can maintain in one place to use across measures.

https://github.com/NREL/openstudio-model-articulation-gem/blob/develop/lib/measures/create_typical_doe_building_from_model/README.md.erb#L37

https://github.com/NREL/openstudio-model-articulation-gem/blob/develop/lib/measures/create_bar_from_doe_building_type_ratios/README.md.erb#L41

https://github.com/NREL/openstudio-model-articulation-gem/tree/develop/lib/measures/SpaceTypeAndConstructionSetWizard

**Pull request merged**
