### PR TITLE
Ashrae 901 2016 2019

### PR DESCRIPTION
**Pull request by DavidGoldwasser**
added two new test to exercise the new versions of 90.1 The tests are not extensive across building types, climate zones, or vintage, but because these are new I wanted to test here before releasing the measure.

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
I updated from develop. Error I'm seeing now is for 2019 but not for 2016, so I may back out the addition of 2016 and try to re-test.

Here is the error
`[openstudio.standards.BoilerHotWater] For Boiler, cannot find boiler properties with search criteria {"template"=>"90.1-2019", "fuel_type"=>"Gas", "fluid_type"=>"Hot Water"}, cannot apply efficiency standard.`

**Comment by DavidGoldwasser** [comment]
@mdahlhausen I removed 2019 thinking there wasn't an error for 2016, but it failed with this error

`[openstudio.model.Model] Could not find refrigeration system properties for: {"template"=>"90.1-2016", "building_type"=>"PrimarySchool", "size_category"=>"Kitchen", "system_type"=>"Low Temperature"}.
`

**Comment by mdahlhausen** [comment]
@DavidGoldwasser what measures did you run to get these errors?

**Comment by DavidGoldwasser** [comment]
@mdahlhausen and @tijcolem I won't merge this yet, since the gem file is modified to a branch, but I can change that and update gem spec after another released standards gem is out.

**Comment by DavidGoldwasser** [comment]
@nllong once merged this is ready to be released as 0.4.2. Then @tijcolem will add it to OpenStudio 3.2 installer, and I will refer to it for measure gem releases.

**Review by nllong — APPROVED** [review]
Look good!

**Pull request merged**
