### PR TITLE
Updated measures that were already in the gem with latest from https:…

### PR DESCRIPTION
**Pull request by bonnema**
…//github.com/NREL/OpenStudio-measures/tree/develop/nrel_published.

### CODE REVIEW

**Comment by nllong** [comment]
The develop of this branch has moved over to supporting only the upcoming OpenStudio 3.0 release. Do these gems need to support 2.x series? If so, then we should point to an LTS branch. Let me konw.

**Comment by DavidGoldwasser** [comment]
@nllong I think there should be a gem release with 2.x support for the upcoming end of march URBANOpt release. ComStock may also need that. I'm fine quickly moving to a 3.x release as well. Note that I know some measures (for example ChangeBuildingLocation used by almost very workflow) will fail tests in 3.x

cc: @kflemin

**Comment by nllong** [comment]
Okay. I’ve added a 0.1.X-LTS branch. We can keep working on this as needed.

**Comment by nllong** [comment]
@DavidGoldwasser -- can you resolve the conflicts so that we can merge? Note that this is getting merged into the 0.1.X-LTS branch which is for OpenStudio 2.x

**Comment by DavidGoldwasser** [comment]
@nllong "Resolve conflicts" isn't enabled for me on GitHub.com for me like it is for other repos. So I can't resolve online. There is no reason for `os_lib_cofee.rb` to be in the repo so I removed it.

**Comment by nllong** [comment]
This PR has been superseded by #47 .

**Pull request closed without merging**
