### PR TITLE
Move runner constants to runner initializer

### PR DESCRIPTION
**Pull request by nllong**
This PR moves the extension constants for running simulations to the initializer of the runner class. 
Prior to this change it was required to set the constants through the child extension which resulted in a constant overload warning.

### CODE REVIEW

**Comment by nllong** [comment]
@TobiasMaile -- any comments on this? I would like to merge this down tomorrow (Tue 10/29) as we are getting ready to release some software that is dependent on it. thanks!

**Comment by TobiasMaile** [comment]
@nllong this looks good, I tested it in the BldgSync context and it works as expected.

**Comment by corymosiman12** [comment]
@nllong is it done this way with the options hash as you are not able to pass **kwargs?  I guess it is relatively similar

**Comment by nllong** [comment]
Yeah. Using the options with defaults is the equivalent to Kwargs.

Il giorno mar 29 ott 2019 alle 10:13 corymosiman12 <notifications@github.com>
ha scritto:

**Comment by corymosiman12** [comment]
@TobiasMaile @nllong working in the seat_analysis branch of edv-experiment-1. I rm Gemfile.lock and rm -rf .bundle/, then tried to bundle install, getting the following: 
```
Bundler could not find compatible versions for gem "openstudio-model-articulation":
  In Gemfile:
    openstudio-model-articulation

    buildingsync was resolved to 0.1.0, which depends on
      openstudio-model-articulation (~> 0.0.1)

Could not find gem 'openstudio-model-articulation (~> 0.0.1)', which is required by gem 'buildingsync', in any of the relevant sources:
  git://github.com/NREL/openstudio-model-articulation-gem.git (at DA@8f6e772)
```

I noticed that I couldn't get this latest commit, which is why I deleted the Gemfile.lock, but what is best way to resolve this??

**Pull request merged**
