### PR TITLE
Update version.rb

### PR DESCRIPTION
**Pull request by DavidGoldwasser**

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@nllong I'm ready to merge this and then crate 0.4.1 release. You have done all the earlier releases, is there an automated approach to the change log and the bullet points you have in the previous releases.

Once this is released then I need to go through all the measure gems to refer to this before I release them.

**Review by nllong — CHANGES_REQUESTED** [review]
When I bump this, I like to add a new entry into the change log that says 

```
# Version 0.4.1 (Unreleased)
```

that way we can create the changelog along the way and know that it hasn't been released yet.

**Comment by nllong** [comment]
> @nllong I'm ready to merge this and then crate 0.4.1 release. You have done all the earlier releases, is there an automated approach to the change log and the bullet points you have in the previous releases.
> 
> Once this is released then I need to go through all the measure gems to refer to this before I release them.

Yes, there is a rake task to populate the change log assuming we are using issues correctly. Otherwise, it is manual.

**Comment by DavidGoldwasser** [comment]
Thanks @nllong I'll try rake task later. I am going to release this today (at least on GitHub, not sure process for getting it to ruby gems. If I don't release it today then I can't finalize and make releases for measure gems.

**Comment by nllong** [comment]
the same command that releases on github releases on rubygems.org. I can release it when you are ready... just let me know.

**Review by tijcolem — APPROVED** [review]

**Comment by tijcolem** [comment]
@DavidGoldwasser  Looks like you want to make use of the latest standards for testing which is https://github.com/NREL/openstudio-standards/tree/v_0_2_13_rc2 

I'll define this in Gemfile.

**Comment by tijcolem** [comment]
@nllong @DavidGoldwasser Well things are passing on CI but with the spec depending on 0.2.13 version of standards, I think `gem install openstudio-extension -v '0.4.1' will as standards doesn't have a release yet. @mdahlhausen I think we'll need a release of 0.2.13-rc2 before this can get merged.

**Comment by tijcolem** [comment]
@nllong @DavidGoldwasser standards released on 0.2.13.rc3 on rubygems. This is been added to as a development dep in
`spec.add_development_dependency 'openstudio-standards', '~> 0.2.13.rc3'`   Assuming this is okay, I think this ready to be merged and 0.4.1 released.

**Comment by DavidGoldwasser** [comment]
@tijcolem when the final standards 0.2.13 comes out do we have to make another extension release.

**Comment by tijcolem** [comment]
@DavidGoldwasser I would think yes, a new ext release so everything is up-to-date. Normally I would say let's wait on this PR until standards 0.12.13 is officially released, but since the ext this is holding up other gems for testing, I think we need to release it. The other options is to release a 0.4.1-rc1 and then move to 0.4.1 once standards is out. 

OpenStudio has the same dilemma as it embeds both ext gem and standards.

**Comment by DavidGoldwasser** [comment]
@nllong I’ll merge this new, do you have a preference on naming of this release. I’d like to release by mid day so I can finalize the measure gems for URBANopt to use.

**Pull request merged**
